site_name: SafeKeys - Documentation

theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.top
    - navigation.path
    - search.highlight
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.code.annotation
    - toc.integrate
    - navigation.sections
    - search.suggest
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/CapelleGab
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/CapelleGab/

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes
  - pymdownx.arithmatex:
      generic: true

copyright: |
  &copy; 2024 <a href="https://github.com/SafeKeys-App"  target="_blank" rel="noopener">SafeKeys Team</a>
